
services:
  # Milvus向量数据库
  milvus:
    image: milvusdb/milvus:v2.5.12
    container_name: flowvo-milvus
    command: ["milvus", "run", "standalone"]
    ports:
      - "19530:19530"  # Milvus gRPC端口
      - "9091:9091"    # Milvus HTTP端口
    environment:
      - ETCD_ENDPOINTS=etcd:2379
      - MINIO_ADDRESS=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    volumes:
      - milvus_data:/var/lib/milvus
    depends_on:
      - etcd
      - minio
    restart: unless-stopped
    networks:
      - flowvo_network

  # etcd存储服务
  etcd:
    image: quay.io/coreos/etcd:v3.5.5
    container_name: flowvo-etcd
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - etcd_data:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    restart: unless-stopped
    networks:
      - flowvo_network

  # MinIO对象存储
  minio:
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    container_name: flowvo-minio
    environment:
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    ports:
      - "9001:9001"    # MinIO控制台
      - "9000:9000"    # MinIO API
    volumes:
      - minio_data:/data
    command: minio server /data --console-address ":9001"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - flowvo_network

  # Milvus Web UI (可选)
  attu:
    image: zilliz/attu:latest
    container_name: flowvo-attu
    ports:
      - "3000:3000"
    environment:
      - MILVUS_URL=milvus:19530
    depends_on:
      - milvus
    restart: unless-stopped
    networks:
      - flowvo_network

volumes:
  milvus_data:
    driver: local
  etcd_data:
    driver: local
  minio_data:
    driver: local

networks:
  flowvo_network:
    driver: bridge 