spring:
  application:
    name: agents

  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

  # 数据库配置（可选，用于存储文档元数据）
  datasource:
    url: jdbc:mysql://localhost:3306/flowvo?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: Aa111111
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: ${OPENAI_BASE_URL}
      embedding:
        options:
          model: ${OPENAI_EMBEDDING_MODEL:text-embedding-ada-002}
    deepseek:
      api-key: ${DEEPSEEK_API_KEY}
      base-url: ${DEEPSEEK_BASE_URL}
      chat:
        enabled: true
        options:
          model: ${DEEPSEEK_CHAT_MODEL:deepseek-chat}
          temperature: 0.8

    zhipuai:
      api-key: ${ZHIPU_API_KEY}
      embedding:
        options:
          model: ${ZHIPU_EMBEDDING_MODEL:embedding-3}
          dimensions: 2048 # 踩坑：openAI千万别写嵌入模型的向量为度

#    vectorstore:
#      milvus:
#        client:
#          host: "localhost"
#          port: 19530
#          username: "root"
#          password: "milvus"
#        database-name: "default"
#        collection-name: "doc_chunk_2048"
##        embedding-dimension: 1536
#        index-type: IVF_FLAT
#        metric-type: COSINE
#        # 启用自动schema初始化，让Spring AI创建默认结构
#        initialize-schema: true

server:
  port: 8081

# 向量化服务配置
embedding:
  # 服务类型：EXTERNAL（外部Python服务）或 OPENAI（OpenAI嵌入模型） 或 ZHIPUAI （ZhiPuAI嵌入模型）
  type: OPENAI
  external:
    # 外部向量化服务URL
    url: http://localhost:8000
    # 连接超时时间（毫秒）
    connect-timeout: 5000
    # 读取超时时间（毫秒）  
    read-timeout: 30000
    # 文本切分配置
    chunk-size: 300
    chunk-overlap: 50

# 日志配置
logging:
  level:
    root: INFO
    org.xue.agents: DEBUG
    # 暂时打开Spring Security的调试日志以排查问题
    org.springframework.security: DEBUG
    org.springframework.boot.autoconfigure: WARN
    # 打开Web请求日志以查看请求路径
    org.springframework.web: DEBUG



