spring:
  config:
    activate:
      on-profile: prompt   # 只有当 --spring.profiles.active=module-a 时，本文件才会被读入

# 提示词配置 - 将所有写死的提示词提取到这里，方便修改和管理
prompts:
  # PixelChat相关提示词
  pixel-chat:
    system: '你是一个友善、有帮助的AI助手。当用户上传文件时，请仔细分析文件内容并提供有用的见解。对于图片文件，请描述你能从文件名和上下文中推断的内容。对于文档文件，请根据提供的文本内容进行分析和回答。'
    file-assistant: '你是一个专业的文件分析助手。请仔细分析用户提供的文件内容，根据文件类型提供相应的帮助：\n- 对于图片文件：描述图片内容、识别文本、分析场景等\n- 对于文档文件：总结内容、提取关键信息、回答相关问题\n- 对于代码文件：分析代码逻辑、识别问题、提供优化建议'

  # 函数调用相关提示词
  function-call:
    system: '你是一个助手，如果需要调用函数，请使用 function_call 返回 JSON。'
    decision: '你是一个助手。判断用户的问题是否需要调用函数。如果需要，请只回复"是"；如果不需要，请只回复"否"。不要提供任何解释或额外信息。'
    selection: '你是一个助手，请根据用户问题选择并返回需要调用的函数。请直接返回function_call字段的JSON格式，**不要**返回多余解释。'
    decision-simple: '你是一个助手。判断用户的问题是否需要调用函数。如果需要，请只回复"Y"；如果不需要，请只回复"N"。不要提供任何解释或额外信息。'

  # 聊天相关提示词
  chat:
    default: '你是一个友善、专业的AI助手，请根据用户的问题提供准确、有用的回答。'
    knowledge-base: '【以下是相关资料，可参考作答】\n{context}\n【用户提问】\n{question}'
    error-fallback: '抱歉，我在处理您的请求时遇到了一些问题。请稍后再试，或者重新描述您的问题。'

  # 图像识别相关提示词
  vision:
    default: '请分析这张图片的内容，描述你所看到的详细信息。'
    with-question: '请根据用户的问题分析这张图片：{question}'
    general: '你是一个专业的图像分析助手，请仔细观察图片并提供详细的描述和分析。'