
spring:
  config:
    activate:
      on-profile: agent   # 只有当 --spring.profiles.active=module-a 时，本文件才会被读入

# Agent配置
agent:
  enabled: true
  maxInteractions: 10
  # openai model
#  defaultModel: gpt-4-turbo
  # deepseek model配置
  defaultModel: deepseek-chat
  systemPrompt: "你是一个智能助手，需要得到用户想要的最终回复时才停止调用function，否则你需要持续响应function_call JSON与function API交互。你可以根据现有的function API来分析如何多次调用得出最终结论"
  temperature: 0.7
  llmApi:
    # openai url
#    key: ${LLM_API_KEY}
#    url: ${LLMAPI_BASE_URL}
    # deepseek url配置
    key: ${LLM_API_KEY}
    url: ${LLMAPI_BASE_URL}
    timeout: 60000

# MCP客户端配置
mcp:
  enabled: true
  heartbeat:
    enabled: false
    interval: 10000 # 心跳检查间隔（毫秒）
  servers:
    mysql:
      name: mcp-mysql  # 服务名称，用于URL拼接
      remote: true    # 本地模式，使用当前应用端口连接
      host: localhost
      port: 50941
      protocol: http
      retry:
        enabled: true
        interval: 10000  # 毫秒
