server:
  port: 8762

spring:
  application:
    name: milvus

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  cloud:
    eureka:
      client:
        service‑url:
          defaultZone: http://localhost:8761/eureka
        fetch‑registry: true
        # 是否自己注册到注册中心
        register‑with‑eureka: true
        enabled: true
      instance:
        instance‑id: ${spring.application.name}_${server.port}
        prefer‑ip‑address: true
        lease-renewal-interval-in-seconds: 30  #服务提供者实例续期时间间隔
        lease-expiration-duration-in-seconds: 90 #服务提供者失效的时间，默认为90秒。

  main:
    allow-bean-definition-overriding: true

logging:
  level:
    org.xue.milvus: DEBUG

proxy:
  host: 127.0.0.1
  port: 7890

local:
  embedding:
    server: http://localhost:8000

